### ISSUE TITLE
number of shots

### ISSUE THREAD

**Issue by leonardthomson** [leonardthomson/Shotboerse#1]
Make it possible to select any number of shots!

**Comment by janneklink** [comment]
Fixed problems were self.all_shots_bought had not dynamic length and set_prices used the global list is_already_cheap which didn't have dynamic length, this global list is now removed

**Comment by janneklink** [comment]
Fixed problems were self.all_shots_bought had not dynamic length and set_prices used the global list is_already_cheap which didn't have dynamic length, this global list is now removed
